version: '3'

services:
    db:
        image: mysql:5.7
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - 9001
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached

    nginx:
        build: nginx
        expose:
            - 80
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
            - ./logs/nginx:/var/log/nginx:cached
        environment: 
            VIRTUAL_HOST: ${VIRTUAL_HOST}

    elk:
        image: willdurand/elk
        expose:
            - 80
        volumes:
            - ./elk/logstash:/etc/logstash:cached
            - ./elk/logstash/patterns:/opt/logstash/patterns:cached
            - ./logs/nginx:/var/log/nginx:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        environment: 
            VIRTUAL_HOST: ${ELK_VIRTUAL_HOST}

volumes:
    db-data:

networks:
    default:
        external:
            name: nginx-proxy