version: '3'

services:
    db:
        image: 'microsoft/mssql-server-linux'
        ports:
            - '1433:1433'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=${MSSQL_PASSWORD}
        volumes:
            - './drive:/mnt/drive'
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - 9001
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached

    nginx:
        build: nginx
        expose:
            - 80
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
            - ./logs/nginx:/var/log/nginx:cached
        environment: 
            VIRTUAL_HOST: ${VIRTUAL_HOST}

    elk:
        image: willdurand/elk
        expose:
            - 80
        volumes:
            - ./elk/logstash:/etc/logstash:cached
            - ./elk/logstash/patterns:/opt/logstash/patterns:cached
            - ./logs/nginx:/var/log/nginx:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        environment: 
            VIRTUAL_HOST: ${ELK_VIRTUAL_HOST}

volumes:
    db-data:

networks:
    default:
        external:
            name: nginx-proxy